import pygame

OPEN_SETTINGS_SCREEN = pygame.USEREVENT + 1
OPEN_MENU_SCREEN = pygame.USEREVENT + 2
OPEN_GAME_SCREEN = pygame.USEREVENT + 3
OPEN_PLAYERS_SCREEN = pygame.USEREVENT + 4
CLICK_CELL = pygame.USEREVENT + 5
CLICK_PIRATE = pygame.USEREVENT + 6
OPEN_FINISH_GAME = pygame.USEREVENT + 7